### ISSUE TITLE
Not all links are downloaded, only the last 1000

### ISSUE THREAD

**Issue by dakanyan** [epitron/delicious-cli#2]
When using /v1/posts/all?, by default, not all the links are downloaded, only the last 1000. According to their documentation, a maximum of 100000 bookmarks can be fetched through the API.

https://github.com/SciDevs/delicious-api/blob/master/api/posts.md#v1postsall

**Comment by epitron** [comment]
Nice! I'll update this when I'm at a computer.

**Comment by epitron** [comment]
Hah! Sorry, I forgot about this issue.

FIXED!
